In [18]:
import numpy as np

lis = [1,1,5,2,356,45,65,98,23,12,56,32,78,12,456,23]

#Making list as array
x = np.array(lis)
print(x)

[  1   1   5   2 356  45  65  98  23  12  56  32  78  12 456  23]


In [ ]:
m = np.array([[4,5,6] , 
              [45,56,78],
              [4,65,98],
              [78,98,56]
              ])

print(m)

print("No of Row & Column: ", m.shape)

[[ 4  5  6]
 [45 56 78]
 [ 4 65 98]
 [78 98 56]]
No of Row & Column:  (4, 3)


In [12]:
# n = np.array(0,1,2) #start at 0 count up by 2, stop before 30

# n

In [ ]:
#reshape chnage the grid layout without altering the total element count or the org. data, whereas resize can change the total element count by truncating elements

n = m.reshape(4,3)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6])

arr.resize((2, 3))
print(arr)

[  1   1   5   2 356  45  65  98  23  12  56  32  78  12 456  23]
[[1 2 3]
 [4 5 6]]


In [30]:
np.zeros([2,3])

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [47]:
m1 = np.matrix([[4,5,6] , 
                [45,56,78],
                [4,65,98]
              ])
m1
print(type(m1))


<class 'numpy.matrix'>


In [ ]:
#print diagonal element: 
print(np.diagonal(m1))

#diagonal element above diagonal element:
print(np.diagonal(m1,1))

#diagonal element below diagonal element:
print(np.diagonal(m1,-1))

#give element above diagonal element:
print(np.diagonal(m1,2))


[ 4 56 98]
[ 5 78]
[45 65]
[6]


In [ ]:
#create ana array using reapeating list
np.array([1,2,3] * 3)


#repeat each element multiple time continously then ',' 
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
#use of Vstack and stack arrays in squencse vertically (row wise)
# p = [[1,1,1],
#      [1,1,1],
#      [1,1,1]]

p = np.ones([3,3], int)         #used to make 1's array like i create above

np.vstack([p,2*p]) #vertical stack

np.hstack([p, 2*p, 5*p, 6*p]) #horizontal stack

array([[1, 1, 1, 2, 2, 2, 5, 5, 5, 6, 6, 6],
       [1, 1, 1, 2, 2, 2, 5, 5, 5, 6, 6, 6],
       [1, 1, 1, 2, 2, 2, 5, 5, 5, 6, 6, 6]])

In [94]:
x = np.array([10,42,34])
y = np.array([41,25,16])

#basic arithmetic operation on array list

print(x+y)
print(x-y)

print(x*y)
print(x/y)

print(x % y)

#Dot product :
print(x@y)   # @ use for dot product like: 1*4 + 2*5 + 3*6 = 32
print(x.dot(y))

#power operation:
z= np.array([y,y**2])
print(z)

#to transport the matrix
print(z.T)

print(z.T.shape)


#use .astype to cast to a specific type
z.astype('f')

[51 67 50]
[-31  17  18]
[ 410 1050  544]
[0.24390244 1.68       2.125     ]
[10 17  2]
2004
2004
[[  41   25   16]
 [1681  625  256]]
[[  41 1681]
 [  25  625]
 [  16  256]]
(3, 2)


array([[  41.,   25.,   16.],
       [1681.,  625.,  256.]], dtype=float32)

In [101]:
#math built in functions

math = np.array([-5,6,8,9,10])
            #     0,1,2,3,4
            #     -5,-4,-3,-2,-1
print(math.sum())

print(math.min())
print(math.max())

#return index of max and min element
print(math.argmax())
print(math.argmin())


28
-5
10
4
0


In [ ]:
#indexing and slicing

arr = np.arange(10)     #its going to print 0-10 numbers
print(arr)

# np.arange(10)**2        it takes 0 to 10 and multiply with 2
# arr[-1]                     it print last index element

print(arr[1:8])             #start at 1 and end at secon last like: 8-1 = 7
print(arr[2::2])            #In a NumPy array, the :: syntax is the extended slicing operator used to skip elements by a specified step size.

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[2 4 6 8]


In [ ]:
r = np.arange(100)
r.resize([10,10])
# print(r)

# print(r[1,2])       show specific element
# print(r[2,2:5])         show row = 2 and element from 2 to 5

print(r[:3, :2])        #till that row and column



[[ 0  1]
 [10 11]
 [20 21]]
