In [1]:
#importing

import numpy as np

In [ ]:
# 1.  Create a constant array 
  # Prints "[[ 7.  7.] 
                #          [ 7.  7.]]" 

p =  np.ones([4,4], int) 

print(np.array([p*7]))

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [30]:
#2. Create an array filled with random values 
         # Might print "[[ 0.91940167  0.08143941] 
         #               [ 0.68744134  0.87236687]]" 

from numpy import random as rm
x = rm.randint(1000, size=(15))

print(x)

[478 278  27 980 537 794 578  22  53 657 189 342 689 653 589]


In [54]:
# 3. Create a NumPy array containing the numbers from 10 to 50. Display: 

arr = np.arange(10,51)

 
# The array 
print(arr)

# Number of elements 
print("No of ele: ", len(arr))

# Shape 
n = arr.shape
print("Shape:", n)

# Dimension 
arr.resize((11, 4))
print("Resizing : ",arr)

# Data type 
print("Datatype: ",type(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
No of ele:  41
Shape: (41,)
Resizing :  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]
 [50  0  0  0]]
Datatype:  <class 'numpy.ndarray'>


In [71]:
# 4. Using NumPy, create: 
 
# A 1D array containing 10 zeros 
dd =  np.zeros([10],int) 
print("10 Zeors: ", dd)

# A 3 × 3 array containing ones 
three =  np.ones([3,3], int) 
print("3 * 3: \n", three)

# A 4 × 4 identity matrix 
iden =  np.eye(4)
print("Identical matrix: \n", iden)

# An array containing numbers from 5 to 50 with a step size of 5. 
ar = np.arange(5,51,5)
print("Skiping: ", ar)

10 Zeors:  [0 0 0 0 0 0 0 0 0 0]
3 * 3: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Identical matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Skiping:  [ 5 10 15 20 25 30 35 40 45 50]


In [98]:
# 5. Create an array containing numbers from 1 to 24. Reshape it into: 

ar = np.arange(1,25)

# 4 × 6 
print("4 * 6: ")
ar.resize((4,6))
print(ar)

# 6 × 4 
print("\n6 * 4: ")
ar.resize((6,4))
print(ar)

# 2 × 3 × 4 
print("\n2 * 3 * 4: ")
ar.resize((2,3,4))
print(ar)


# Display the shape and ndim of each result.
ar.shape

4 * 6: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

6 * 4: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

2 * 3 * 4: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


(2, 3, 4)

In [102]:
# 6. Consider: 

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81]) 
 
# Write NumPy statements to display: 
 
# First element 
print(marks[0])
# Last element  
print(marks[-1])
# Third element 
print(marks[2]) 
# First four elements  
print(marks[0:4])
# Last three elements  
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


In [105]:
# 7. Create: 
a = np.array([10, 20, 30, 40, 50]) 
b = np.array([5, 10, 15, 20, 25]) 
# Calculate: 
# a + b

print(a+b) 
# a - b 
print(a-b)
# a * b 
print(a*b)
# a / b 
print(a/b)
# Square of every element in a 
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]
