In [3]:
#importing

import numpy as np

In [4]:
# 1.  Create a constant array 
  # Prints "[[ 7.  7.] 
                #          [ 7.  7.]]" 

p =  np.ones([4,4], int) 

print(np.array([p*7]))

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [5]:
#2. Create an array filled with random values 
         # Might print "[[ 0.91940167  0.08143941] 
         #               [ 0.68744134  0.87236687]]" 

from numpy import random as rm
x = rm.randint(1000, size=(15))

print(x)

[291 632 770 908 534 878 444 547 810 106 718 772 545 152  86]


In [6]:
# 3. Create a NumPy array containing the numbers from 10 to 50. Display: 

arr = np.arange(10,51)

 
# The array 
print(arr)

# Number of elements 
print("No of ele: ", len(arr))

# Shape 
n = arr.shape
print("Shape:", n)

# Dimension 
arr.resize((11, 4))
print("Resizing : ",arr)

# Data type 
print("Datatype: ",type(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
No of ele:  41
Shape: (41,)
Resizing :  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]
 [50  0  0  0]]
Datatype:  <class 'numpy.ndarray'>


In [7]:
# 4. Using NumPy, create: 
 
# A 1D array containing 10 zeros 
dd =  np.zeros([10],int) 
print("10 Zeors: ", dd)

# A 3 × 3 array containing ones 
three =  np.ones([3,3], int) 
print("3 * 3: \n", three)

# A 4 × 4 identity matrix 
iden =  np.eye(4)
print("Identical matrix: \n", iden)

# An array containing numbers from 5 to 50 with a step size of 5. 
ar = np.arange(5,51,5)
print("Skiping: ", ar)

10 Zeors:  [0 0 0 0 0 0 0 0 0 0]
3 * 3: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Identical matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Skiping:  [ 5 10 15 20 25 30 35 40 45 50]


In [8]:
# 5. Create an array containing numbers from 1 to 24. Reshape it into: 

ar = np.arange(1,25)

# 4 × 6 
print("4 * 6: ")
ar.resize((4,6))
print(ar)

# 6 × 4 
print("\n6 * 4: ")
ar.resize((6,4))
print(ar)

# 2 × 3 × 4 
print("\n2 * 3 * 4: ")
ar.resize((2,3,4))
print(ar)


# Display the shape and ndim of each result.
ar.shape

4 * 6: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

6 * 4: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

2 * 3 * 4: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


(2, 3, 4)

In [9]:
# 6. Consider: 

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81]) 
 
# Write NumPy statements to display: 
 
# First element 
print(marks[0])
# Last element  
print(marks[-1])
# Third element 
print(marks[2]) 
# First four elements  
print(marks[0:4])
# Last three elements  
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


In [10]:
# 7. Create: 
a = np.array([10, 20, 30, 40, 50]) 
b = np.array([5, 10, 15, 20, 25]) 
# Calculate: 
# a + b

print(a+b) 
# a - b 
print(a-b)
# a * b 
print(a*b)
# a / b 
print(a/b)
# Square of every element in a 
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [25]:
# 8. Given:
salary = np.array([25000, 32000, 28000, 45000,50000, 38000, 42000, 30000])

# Find:
# Total salary
print("Sum of salary: ",salary.sum())

# Average salary
print("Average Salary: ",np.average(salary))

# Highest salary
print("Highest Salary: ",salary.max())

# Lowest salary
print("Lowest salary: ", salary.min())

# Median salary
print("Median Salary: ", np.median(salary))

# Standard deviation
print(f"standard Deviation: {np.std(salary):.2f}")




Sum of salary:  290000
Average Salary:  36250.0
Highest Salary:  50000
Lowest salary:  25000
Median Salary:  35000.0
standard Deviation: 8317.90


In [ ]:
# 9. Given: 
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
# Using NumPy boolean indexing, find:

# Marks greater than 75

# Marks between 50 and 80

# Number of students who scored below 50

# Percentage of students who scored 60 or above

# Do not use a Python for loop.


In [ ]:
# 10. The following array contains marks of four students in three subjects:
marks = np.array([
[80, 75, 90],
[65, 70, 72],
[88, 92, 85],
[55, 60, 58]
])

# Calculate:
# Total marks of each student
# Average marks of each student
# Average marks in each subject
# Student with the highest total
# Highest mark in each subject.


In [ ]:
# 11. Create:
A = np.array([
[1, 2],
[3, 4]
])
B = np.array([
[5, 6],
[7, 8]
])

# Perform:
# Matrix addition
# Element-wise multiplication
# Matrix multiplication
# Transpose of A.
# explain the difference between:
# A * B and A @ B


In [ ]:
# 12. Daily temperatures for two weeks are:

temperature = np.array([
31, 32, 33, 35, 36, 34, 32,
30, 29, 31, 33, 35, 37, 36
])

# Find:
# Mean temperature
# Maximum and minimum temperatures
# Number of days above the average temperature
# Temperatures greater than 34°C
# Difference between maximum and minimum
# Standard deviation


In [ ]:
# 13. Monthly sales of a company are:
sales = np.array([
12000, 15000, 17000, 14000,
18000, 21000, 19000, 22000,
25000, 23000, 26000, 28000
])
# Determine:
# Total annual sales
# Average monthly sales
# Month with the highest sales
# Month with the lowest sales
# Number of months with sales above ₹20,000
# Percentage increase from January to December
# Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.

In [ ]:
# 14. Consider marks of five students in four subjects:
marks = np.array([
[78, 85, 90, 88],
[65, 70, 72, 68],
[92, 88, 95, 91],
[55, 60, 58, 62],
[80, 75, 82, 79]
])
# Write a NumPy program that calculates:
# Total marks of every student
# Average of every student
# Average mark for every subject
# Highest-scoring student
# Lowest-scoring student
# Students whose average is greater than 80
# Overall class average

# Then assign a performance category based on average:
# | Average | Category |
# | -------: | ----------------- |
# | ≥ 85 | Excellent |
# | 70–84.99 | Good |
# | 50–69.99 | Average |
# | < 50 | Needs Improvement |
# Challenge: Try assigning these categories using np.where() or np.select() instead of a Python
# loop.

In [ ]:
# 15. Generate 20 random integers between 1 and 100.


In [ ]:
# 16. Find all even numbers from the generated array.


In [ ]:
# 17. Replace values below 50 with 0.


In [ ]:
# 18. Sort the array in ascending and descending order.


In [ ]:
# 19. Find unique values and their frequencies.


In [ ]:
# 20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.


In [ ]:
# 21. Take your own example to normalize an array.


In [ ]:
# 22. use your own data to standardize an array.


In [ ]:
# 23. Create a NumPy array containing 100 random exam marks and determine how many
# students fall into the ranges 0–39, 40–59, 60–79, and 80–100.


In [ ]:
# 24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy
# array