In [197]:
#importiag

import numpy as np

In [198]:
# 1.  Create a constaat array 
  # Prints "[[ 7.  7.] 
                #          [ 7.  7.]]" 

p =  np.ones([4,4], int) 

print(np.array([p*7]))

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [199]:
#2. Create an array filled with random values 
         # Might print "[[ 0.91940167  0.08143941] 
         #               [ 0.68744134  0.87236687]]" 

from numpy import random as rm
x = rm.randint(1000, size=(15))

print(x)

[671 265 560 105 912 920 265 112 488 868  21 258 643 843 721]


In [200]:
# 3. Create a NumPy array containing the numbers from 10 to 50. Display: 

arr = np.arange(10,51)

 
# The array 
print(arr)

# Number of elements 
print("No of ele: ", len(arr))

# Shape 
n = arr.shape
print("Shape:", n)

# Dimension 
arr.resize((11, 4))
print("Resizing : ",arr)

# Data type 
print("Datatype: ",type(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
No of ele:  41
Shape: (41,)
Resizing :  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]
 [50  0  0  0]]
Datatype:  <class 'numpy.ndarray'>


In [201]:
# 4. Using NumPy, create: 
 
# A 1D array containing 10 zeros 
dd =  np.zeros([10],int) 
print("10 Zeors: ", dd)

# A 3 × 3 array containing ones 
three =  np.ones([3,3], int) 
print("3 * 3: \n", three)

# A 4 × 4 identity matrix 
iden =  np.eye(4)
print("Identical matrix: \n", iden)

# An array containing numbers from 5 to 50 with a step size of 5. 
ar = np.arange(5,51,5)
print("Skiping: ", ar)

10 Zeors:  [0 0 0 0 0 0 0 0 0 0]
3 * 3: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Identical matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Skiping:  [ 5 10 15 20 25 30 35 40 45 50]


In [202]:
# 5. Create an array containing numbers from 1 to 24. Reshape it into: 

ar = np.arange(1,25)

# 4 × 6 
print("4 * 6: ")
ar.resize((4,6))
print(ar)

# 6 × 4 
print("\n6 * 4: ")
ar.resize((6,4))
print(ar)

# 2 × 3 × 4 
print("\n2 * 3 * 4: ")
ar.resize((2,3,4))
print(ar)


# Display the shape and ndim of each result.
ar.shape

4 * 6: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

6 * 4: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

2 * 3 * 4: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


(2, 3, 4)

In [203]:
# 6. Consider: 

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81]) 
 
# Write NumPy statements to display: 
 
# First element 
print(marks[0])
# Last element  
print(marks[-1])
# Third element 
print(marks[2]) 
# First four elements  
print(marks[0:4])
# Last three elements  
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


In [204]:
# 7. Create: 
a = np.array([10, 20, 30, 40, 50]) 
b = np.array([5, 10, 15, 20, 25]) 
# Calculate: 
# a + b

print(a+b) 
# a - b 
print(a-b)
# a * b 
print(a*b)
# a / b 
print(a/b)
# Square of every element in a 
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [205]:
# 8. Given:
salary = np.array([25000, 32000, 28000, 45000,50000, 38000, 42000, 30000])

# Find:
# Total salary
print("Sum of salary: ",salary.sum())

# Average salary
print("Average Salary: ",np.average(salary))

# Highest salary
print("Highest Salary: ",salary.max())

# Lowest salary
print("Lowest salary: ", salary.min())

# Median salary
print("Median Salary: ", np.median(salary))

# Standard deviation
print(f"standard Deviation: {np.std(salary):.2f}")




Sum of salary:  290000
Average Salary:  36250.0
Highest Salary:  50000
Lowest salary:  25000
Median Salary:  35000.0
standard Deviation: 8317.90


In [206]:
# 9. Given: 
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
# Using NumPy boolean indexing, find:

import numpy as np

# Marks greater than 75
res = marks[marks > 75]
print("Marks > 75: ",res)

# Marks between 50 and 80
res1 = marks[(marks >= 50) & (marks <= 80)]
print("Marks between 50 and 80: ",res1)

# Number of students who scored below 50
res2 = np.sum(marks < 50)
print("Below 50: ",res2)

# Percentage of students who scored 60 or above
res3 = np.mean(marks >= 60) * 100
print("> 60: ",res3, "%")

Marks > 75:  [78 89 90 76 84]
Marks between 50 and 80:  [78 67 55 76]
Below 50:  3
> 60:  60.0 %


In [208]:
# 10. The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

# Total marks of each student
res = marks.sum(axis=1)
print("Total marks of each student: ",res)

# Average marks of each student
res1 = marks.mean(axis=1)
print("Average marks of each student: ",res1)

# Average marks in each subject
res2 = marks.mean(axis=0)
print("Average marks in each subject: ",res2)

# Student with the highest total
res3 = np.argmax(res)
print("Student with the highest total: ",res3)

# Highest mark in each subject
res4 = marks.max(axis=0)
print("Highest mark in each subject: ",res4)


Total marks of each student:  [245 207 265 173]
Average marks of each student:  [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject:  [72.   74.25 76.25]
Student with the highest total:  2
Highest mark in each subject:  [88 92 90]


In [209]:
# 11. Create:
A = np.array([
[1, 2],
[3, 4]
])

B = np.array([
[5, 6],
[7, 8]
])

# Perform:
# Matrix addition
res = A + B
print("Matrix addition: \n",res)

# Element-wise multiplication
res1 = A * B
print("Element-wise multiplication: \n",res1)

# Matrix multiplication
res2 = A @ B
print("Matrix multiplication: \n",res2)

# Transpose of A
res3 = A.T
print("Transpose of A: \n",res3)


Matrix addition: 
 [[ 6  8]
 [10 12]]
Element-wise multiplication: 
 [[ 5 12]
 [21 32]]
Matrix multiplication: 
 [[19 22]
 [43 50]]
Transpose of A: 
 [[1 3]
 [2 4]]


In [210]:
# 12. Daily temperatures for two weeks are:

temperature = np.array([
31, 32, 33, 35, 36, 34, 32,
30, 29, 31, 33, 35, 37, 36
])

# Find:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

# Mean temperature
res = np.mean(temperature)
print("Mean temperature: ",res)

# Maximum and minimum temperatures
res1 = np.max(temperature)
res2 = np.min(temperature)
print("Maximum temperature: ",res1)
print("Minimum temperature: ",res2)

# Number of days above the average temperature
res3 = np.sum(temperature > res)
print("Days above average: ",res3)

# Temperatures greater than 34°C
res4 = temperature[temperature > 34]
print("Temperatures > 34: ",res4)

# Difference between maximum and minimum
res5 = res1 - res2
print("Max - Min difference: ",res5)

# Standard deviation
res6 = np.std(temperature)
print("Standard deviation: ",res6)


Mean temperature:  33.142857142857146
Maximum temperature:  37
Minimum temperature:  29
Days above average:  6
Temperatures > 34:  [35 36 35 37 36]
Max - Min difference:  8
Standard deviation:  2.356060357495806


In [211]:
# 13. Monthly sales of a company are:
sales = np.array([
12000, 15000, 17000, 14000,
18000, 21000, 19000, 22000,
25000, 23000, 26000, 28000
])
# Determine:
# Total annual sales
res = np.sum(sales)
print("Total annual sales: ",res)

# Average monthly sales
res1 = np.mean(sales)
print("Average monthly sales: ",res1)

# Month with the highest sales
res2 = np.argmax(sales) + 1
print("Month with highest sales: ",res2)

# Month with the lowest sales
res3 = np.argmin(sales) + 1
print("Month with lowest sales: ",res3)

# Number of months with sales above ₹20,000
res4 = np.sum(sales > 20000)
print("Months with sales above 20000: ",res4)

# Percentage increase from January to December
res5 = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Percentage increase Jan to Dec: ",res5, "%")

Total annual sales:  240000
Average monthly sales:  20000.0
Month with highest sales:  12
Month with lowest sales:  1
Months with sales above 20000:  6
Percentage increase Jan to Dec:  133.33333333333331 %


In [212]:
# 14. Consider marks of five students in four subjects:
marks = np.array([
[78, 85, 90, 88],
[65, 70, 72, 68],
[92, 88, 95, 91],
[55, 60, 58, 62],
[80, 75, 82, 79]
])

# Total marks of every student
res = marks.sum(axis=1)
print("Total marks of every student: ",res)

# Average of every student
res1 = marks.mean(axis=1)
print("Average of every student: ",res1)

# Average mark for every subject
res2 = marks.mean(axis=0)
print("Average mark for every subject: ",res2)

# Highest-scoring student
res3 = np.argmax(res)
print("Highest-scoring student (index): ",res3)

# Lowest-scoring student
res4 = np.argmin(res)
print("Lowest-scoring student (index): ",res4)

# Students whose average is greater than 80
res5 = res1[res1 > 80]
print("Students with average > 80: ",res5)

# Overall class average
res6 = np.mean(marks)
print("Overall class average: ",res6)

# Performance category based on average, using np.select()
conditions = [
    res1 >= 85,
    (res1 >= 70) & (res1 < 85),
    (res1 >= 50) & (res1 < 70)
]
choices = ["Excellent", "Good", "Average"]
res7 = np.select(conditions, choices, default="Needs Improvement")
print("Performance category: ",res7)

Total marks of every student:  [341 275 366 235 316]
Average of every student:  [85.25 68.75 91.5  58.75 79.  ]
Average mark for every subject:  [74.  75.6 79.4 77.6]
Highest-scoring student (index):  2
Lowest-scoring student (index):  3
Students with average > 80:  [85.25 91.5 ]
Overall class average:  76.65
Performance category:  ['Excellent' 'Average' 'Excellent' 'Average' 'Good']


In [213]:
# 15. Generate 20 random integers between 1 and 100.

random = np.random.randint(1, 101, size=20)
print("Random integers: ",random)

Random integers:  [56 72 85 70 39 79 84 83 29 54 31 72 19 25 46 59  8  6 73 84]


In [215]:
# 16. Find all even numbers from the generated array.
even = random_numbers[random_numbers % 2 == 0]
print("Even numbers: ",even)

Even numbers:  [76 94  6 18 20  8 22 96 96 14 56 86]


In [216]:
# 17. Replace values below 50 with 0.
arr = np.random.randint(1, 101, size=20)
print("Original array: ", arr)

arr[arr < 50] = 0
print("After replacing values below 50 with 0: ", arr)

Original array:  [63 46  2 42 42 58 24 13 54 84 81 47  2 38  6 70 29 34 92 72]
After replacing values below 50 with 0:  [63  0  0  0  0 58  0  0 54 84 81  0  0  0  0 70  0  0 92 72]


In [217]:
# 18. Sort the array in ascending and descending order.
asc = np.sort(arr)
desc = np.sort(arr)[::-1]
print("Ascending order: ", asc)
print("Descending order: ", desc)

Ascending order:  [ 0  0  0  0  0  0  0  0  0  0  0  0 54 58 63 70 72 81 84 92]
Descending order:  [92 84 81 72 70 63 58 54  0  0  0  0  0  0  0  0  0  0  0  0]


In [218]:
# 19. Find unique values and their frequencies.
uniques, counts = np.unique(arr, return_counts=True)
print("Unique values: ", uniques)
print("Frequencies: ", counts)

Unique values:  [ 0 54 58 63 70 72 81 84 92]
Frequencies:  [12  1  1  1  1  1  1  1  1]


In [219]:
# 20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.
matrix = np.random.randint(1, 101, size=(5, 5))
rows = matrix.mean(axis=1)
cols = matrix.mean(axis=0)
print("Matrix:\n", matrix)
print("Row-wise means: ", rows)
print("Column-wise means: ", cols)

Matrix:
 [[22 14 87 15 68]
 [38 52 58 28 81]
 [21 83 51 49 47]
 [83 97 79 60 36]
 [16 31 85 87 27]]
Row-wise means:  [41.2 51.4 50.2 71.  49.2]
Column-wise means:  [36.  55.4 72.  47.8 51.8]


In [220]:
# 21. Take your own example to normalize an array.
data = np.array([10, 20, 30, 40, 50])
normalized = (data - data.min()) / (data.max() - data.min())
print("Original data: ", data)
print("Normalized data (0 to 1): ", normalized)

Original data:  [10 20 30 40 50]
Normalized data (0 to 1):  [0.   0.25 0.5  0.75 1.  ]


In [221]:
# 22. use your own data to standardize an array.
data2 = np.array([12, 15, 18, 22, 25, 30])
standardized = (data2 - data2.mean()) / data2.std()
print("Original data: ", data2)
print("Standardized data (mean=0, std=1): ", standardized)

Original data:  [12 15 18 22 25 30]
Standardized data (mean=0, std=1):  [-1.37205325 -0.87811408 -0.38417491  0.27441065  0.76834982  1.59158177]


In [222]:
# 23. Create a NumPy array containing 100 random exam marks and determine how many
# students fall into the ranges 0–39, 40–59, 60–79, and 80–100.
exam_marks = np.random.randint(0, 101, size=100)

range1 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range2 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range3 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range40 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("0-39: ", range1)
print("40-59: ", range2)
print("60-79: ", range3)
print("80-100: ", range40)

0-39:  42
40-59:  24
60-79:  18
80-100:  16


In [226]:
# 24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy
# array

import time

a = 1_000_000
py_l = list(range(a))
np_ar = np.arange(a)

start = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time() - start

start = time.time()
np_result = np_array * 2
np_time = time.time() - start

print("Python list time: ", py_time, "seconds")
print("NumPy array time: ", np_time, "seconds")
print("NumPy is faster by approximately: ", round(py_time / np_time, 2), "x")

Python list time:  0.11250567436218262 seconds
NumPy array time:  0.004526853561401367 seconds
NumPy is faster by approximately:  24.85 x
