In [138]:
# # work on other do dataset
# bestseller
# Groceris

In [139]:
import pandas as ps
import numpy as nm
import matplotlib.pyplot as plt

In [140]:
#importing data:

df = ps.read_csv("../data/bestsellers.csv")
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction


In [141]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    str    
 1   Author       550 non-null    str    
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    str    
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB


In [142]:
df.isnull().sum()

# null_rows = df[df.isnull().all(axis=1)]
# print(null_rows)

Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [143]:
print("Independent variable, X:")
x = df.iloc[:, [2, 3, 4, 5]].values     # User Rating, Reviews, Price, Year
print(x)

print("Dependent variable, Y:")
y = df.iloc[:, 6].values                 # Genre (Fiction / Non Fiction)
print(y)

Independent variable, X:
[[4.7000e+00 1.7350e+04 8.0000e+00 2.0160e+03]
 [4.6000e+00 2.0520e+03 2.2000e+01 2.0110e+03]
 [4.7000e+00 1.8979e+04 1.5000e+01 2.0180e+03]
 ...
 [4.7000e+00 1.4331e+04 8.0000e+00 2.0170e+03]
 [4.7000e+00 1.4331e+04 8.0000e+00 2.0180e+03]
 [4.7000e+00 1.4331e+04 8.0000e+00 2.0190e+03]]
Dependent variable, Y:
<StringArray>
['Non Fiction',     'Fiction', 'Non Fiction',     'Fiction', 'Non Fiction',
     'Fiction',     'Fiction',     'Fiction', 'Non Fiction',     'Fiction',
 ...
     'Fiction',     'Fiction',     'Fiction',     'Fiction',     'Fiction',
     'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction']
Length: 550, dtype: str


In [144]:
print("Duplicate Values: ", df.duplicated().sum())

Duplicate Values:  0


In [145]:
from sklearn.impute import SimpleImputer
import numpy as nm

#handling missing value of X
impute = SimpleImputer(missing_values=nm.nan, strategy='mean')
x = impute.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=45)



In [146]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=45)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

In [147]:
from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy * 100, "%")
print(classification_report(y_test, y_pred))

Accuracy: 70.0 %
              precision    recall  f1-score   support

     Fiction       0.68      0.51      0.58        45
 Non Fiction       0.71      0.83      0.77        65

    accuracy                           0.70       110
   macro avg       0.69      0.67      0.67       110
weighted avg       0.70      0.70      0.69       110

